### ISSUE TITLE
UTF8 problem in Frontend

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#6]
The import has a problem with UTF8: In the FE there are strange outputs coming. See printscreen.
![utf8](https://cloud.githubusercontent.com/assets/17588253/16001735/210b2c4e-3154-11e6-913c-28af85b638ee.png)

**Comment by angeloprevitali** [comment]
The UTF-8 problem is still NOT working. See printscreen. Now the special characters were deleted instead of beeing displayed after uploading a new CSV file.
![bakerlist-utf8](https://cloud.githubusercontent.com/assets/17588253/16644743/6f6f1aa2-441f-11e6-8fc9-cfbccf00d334.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Inprogress
We have tried all the ways Code Encode/Decode, setting for UTF 8 but still it's not working, We are more trying it. 
We will definitely complete it by Monday.

Regards.
Thank You.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Can you please send us the new CSV file
You can see there problems in current version - http://www.awesomescreenshot.com/07060gj496

Regards.
Thank you.

**Comment by jigneshnitsan** [comment]
Hello Angelo
Good Evening.

- CSV file
The current CSV file is not proper so please check with proper CSV file. So please ask for the correct CSV file to client.

- Special Character issue
We have corrected this issue by changing in CSV file. Please see attached CSV file that we have imported.
[adresslist-swissbaker.zip](https://github.com/NetConsultAG/netc_bakerlist/files/361535/adresslist-swissbaker.zip)
Screenshot - http://prntscr.com/bsdzaz

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok. Our customer sent a corrupt file and we did not recognized it. We uploaded a correct CSV and now the frontend it works correctly.

**Comment by angeloprevitali** [comment]
Still not working! Have to REopen this issue. Even with your uploaded file it will NOT work due to YOUR CSV has special characters in the CSV. Please fix this issue. I attached the revised file from our customer here for testing purposes.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message.

It seems you forgot to attach the CSV file, Can you please resend the file here?

Regards.

**Comment by angeloprevitali** [comment]
The CSV file is uploaded already. https://github.com/NetConsultAG/netc_bakerlist/files/363737/Adressliste_Internet_Juni_16.zip

**Comment by michelrossier** [comment]
@jigneshnitsan Can you let us know when you will have time to look into this charset problem? I just tested with a clear utf-8 file and can confirm that it doesn't work. The special chars are still displayed wrong.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Please check these screenshots > http://awesomescreenshot.com/08960ww235

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
We just downloaded the latest files from GitHub, installed it, cleaned cache everywhere and tried another test again with the CSV upload: Still not working with the UTF8 problem. See printscreens
![bakerlist-be-error-utf-8-1](https://cloud.githubusercontent.com/assets/17588253/16906951/3730c5fc-4cbf-11e6-8dba-ff13ab4225ce.png)
![Uploading bakerlist-be-error-utf-8-2.png…]()

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

@UTF 
Status > Done
Screenshot > http://www.awesomescreenshot.com/09f617scc5
Screenshot > http://prntscr.com/bv86zh


Regards.

**Comment by angeloprevitali** [comment]
Works now! Great!
